use_frameworks!

target 'RRPager_Example' do
  pod 'RRPager', :path => '../'

  target 'RRPager_Tests' do
    inherit! :search_paths

    pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
  end
end
